name: Sync Fork

on:
  schedule:
    - cron: '23 23 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: themicr1
          base: master
          head: master
